language: ruby
rvm:
  - 2.3
sudo: required
before_install:
  - sudo update-ca-certificates
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --check-favicon --check-html --http-status-ignore 999
