language: ruby
sudo: required
before_install:
  - sudo update-ca-certificates
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
script:
  - bundle install
  - bundle exec jekyll build
  - bundle exec rake
