# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Bernardo Sulzbach's Website
tagline:             The website of a software developer
description:         >
  A generic-purpose personal website and blog about computer science and
  software engineering.
url:                 http://mafagafogigante.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Bernardo Sulzbach
  url:               https://github.com/mafagafogigante
  email:             mafagafogigante@gmail.com

# Custom vars
version:             1.0.0
