# Permalinks
permalink: /:title/

# Setup
title: Bernardo Sulzbach
description: Computers and Mathematics
repository: https://github.com/mafagafogigante/mafagafogigante.github.io/
url: http://www.mafagafogigante.org
baseurl: ""

# Markdown
kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

# Gems
gems:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: "page/:num"

# About/contact
author:
  name: Bernardo Sulzbach
  url: https://github.com/mafagafogigante
  email: mafagafogigante@gmail.com
