# Permalinks
permalink: /:title/

# Setup
title: Bernardo Sulzbach's Website
description: Discourses on computers, software, and mathematics.
repository: https://github.com/bernardosulzbach/bernardosulzbach.github.io/
url: http://www.bernardosulzbach.com
baseurl: ""

# Markdown
kramdown:
  input: GFM
  auto_ids: false
  hard_wrap: false

highlighter: rouge

# Plugins
plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-sitemap

# Pagination
paginate: 10
paginate_path: "page/:num"

# About/contact
author:
  name: Bernardo Sulzbach
  url: https://github.com/bernardosulzbach
  email: bernardo@bernardosulzbach.com
