# Permalinks
permalink: pretty

# Setup
title: Bernardo Sulzbach's Website
tagline: The website of a software developer
description: A blog about computer science and software engineering.
repository: https://github.com/mafagafogigante/mafagafogigante.github.io/
url: https://mafagafogigante.org
baseurl: ""

# Markdown
kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge

# Gems
gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "page/:num"

# About/contact
author:
  name: Bernardo Sulzbach
  url: https://github.com/mafagafogigante
  email: mafagafogigante@gmail.com
